#+title: Nix

#+begin_quote
Also see [[../concept/os.org][OS]], [[../tool/systemd.org][systemd]] and [[../tool/proxmox.org][Proxmox]]
#+end_quote

/A previous note can be found at [[https://gist.github.com/ryuheechul/a0bd4e4b69565da86301ee8cc26311e1][my gist - nix.md]]./

Nix the language is only a part (but important of course) of the whole Nix ecosystem.
It is tricky to wrap your head around when you face this first time as also there is a lot of information not just the lack of familiarity with other "usual" tools.
But it's a very powerful tool that allow you to setup reproducible computer environment which reduces time of customizing new environemt greatly when switching devices.
This also helps minizes the gap between Linux and macOS which gives you the illusion of almost forgetting that you are on different platforms in terms of being able to use the same exact packages.
It can manage things in a lot of different ways and most popluar things to do is manage operating system and packages.

My nix configuration is mostly at https://github.com/ryuheechul/dotfiles/tree/master/nix.

* There are many official and unofficial articles on Nix which I will add more here over time.
I also wrote an article sometime ago when I first tried Nix as well

- https://dev.to/ryuheechul/don-t-give-up-on-nix-just-yet-37mh
- https://stephank.nl/p/2020-06-01-a-nix-primer-by-a-newcomer.html
- https://xyno.space/post/nix-darwin-introduction
- https://github.com/hlissner/dotfiles#frequently-asked-questions
- https://nixos.wiki/wiki/Flakes
- https://www.tweag.io/blog/2020-05-25-flakes/
- https://serokell.io/blog/practical-nix-flakes
- https://zero-to-nix.com/
- https://github.com/justinwoo/nix-shorts
- [[https://github.com/alexbakker/log4shell-tools][A simple flake example that build with golang - log4shell-tools]]
- https://myme.no/posts/2020-01-26-nixos-for-development.html
- https://determinate.systems/posts/nix-run
- https://ianthehenry.com/posts/how-to-learn-nix/introduction/
- https://nixos.org/manual/nix/stable/language/constructs
- https://summer.nixos.org/blog/callpackage-a-tool-for-the-lazy/

* Flake Cheatsheets
#+begin_src makefile
.PHONY: show
show:
	nix flake show github:ryuheechul/hexto256

.PHONY: build
build:
	nix build github:ryuheechul/hexto256

.PHONY: run # https://determinate.systems/posts/nix-run
run:
	nix run github:ryuheechul/hexto256

.PHONY: shell
shell:
	nix shell github:ryuheechul/hexto256 -c hexto256
#+end_src

* NixOS
- https://nixos.wiki/wiki/NixOS_as_a_desktop
- https://msucharski.eu/posts/application-isolation-nixos-containers/
- https://github.com/ryuheechul/dotfiles/tree/master/nix/nixos
- https://nixos.wiki/wiki/Storage_optimization
- https://www.tweag.io/blog/2023-02-09-nixos-vm-on-macos/
- (read below before add)
- https://nixos.wiki/wiki/C
- https://discourse.nixos.org/t/what-version-of-gcc-does-nix-use/17647/4
- https://stackoverflow.com/questions/75420729/importerror-libstdc-so-6-cannot-open-shared-object-file-no-such-file-or-dir
- https://jdheyburn.co.uk/blog/nix-cheat-sheet/
- https://fnordig.de/til/nix/remote-builds.html
- [[https://taoofmac.com/space/blog/2024/08/17/1530][Running NixOS on Proxmox LXC]]
- https://search.nixos.org/options?channel=unstable&show=security.wrappers&query=wrappers
- https://joinemm.dev/blog/yubikey-nixos-guide
- https://nixcademy.com/posts/nixos-nspawn/
- https://github.com/SaumonNet/proxmox-nixos
