#+title: Matrix

https://matrix.org/
An open network for secure, decentralized communication

https://matrix.org/bridges/
A way to allow interop with other platforms

https://www.beeper.com/
- it appears to be the simplest way to delegate all the setting up of bridges and have a consistent experience across all platforms.
- $10 per month
- it's probably cheaper to pay this and see how it feels like to use other messages via matrix than actually setting things up manually.

Context on beeper - https://medium.com/@ericmigi/the-universal-communication-bus-42dfb9a141ad

* My current thought on all this
It's definately exiciting to observe that such thing exist to connect siloed network as I'm definately not a fan of the reality of having to switch back and forth of multiple different chat apps.
I'm curious to try this out and see if really improve my daily life or not. At the same time I also already have a feeling that this is still an early stage thing (even after great progress so far), so bumpy road should be expected.
